# Generated by Django 3.0.4 on 2020-03-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='name',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
