# Generated by Django 3.0.4 on 2020-04-01 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_auto_20200401_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='baby',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diary', to='diaries.Baby'),
        ),
    ]
