# Generated by Django 3.0.4 on 2020-03-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_baby_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='name',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
