# Generated by Django 3.0.4 on 2020-03-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0003_auto_20200330_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
