# Generated by Django 3.0.4 on 2020-04-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0003_auto_20200401_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='text',
        ),
    ]
