# Generated by Django 3.0.4 on 2020-04-02 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babies', '0001_initial'),
        ('diaries', '0004_remove_diary_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='baby',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diary', to='babies.Baby'),
        ),
        migrations.DeleteModel(
            name='Baby',
        ),
    ]
