# Generated by Django 3.0.4 on 2020-04-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babies', '0003_auto_20200402_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
