# Generated by Django 3.0.4 on 2020-04-12 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('babies', '0004_auto_20200406_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Baby_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
